apiVersion: v2
name: archive-node
description: A Helm chart for Mina Protocol's archive node
type: application
version: 0.5.0
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - enable toggle of local daemon and associated postgresDB deployments
dependencies:
  - name: postgresql
    version: "*"
    repository: "https://charts.bitnami.com/bitnami"
    condition: archive.enablePostgresDB
  - name: common-utilities
    version: 0.0.8
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- archive
- postgres
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/helm/archive-node
