{{- if .Values.deployment.runtimeConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: daemon-config
  labels:
    app: {{ .Values.deployment.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  daemon.json: {{ .Values.deployment.runtimeConfig | quote }}
{{- end }}
