apiVersion: v2
name: plain-node
description: A Helm chart for Mina Protocol's plain nodes
type: application
version: 1.0.4
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - Update common-utils chart
dependencies:
  - name: common-utilities
    version: "*"
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/helm/plain-node
