testnetName: "testnet"
mina:
  runtimeConfig:
  generateGenesisProof: true
  logPrecomputedBlocks: true
  logTxnPoolGossip: false
  maxConnections: 200
  image: gcr.io/o1labs-192920/mina-daemon:1.2.0beta8-5b35b27-devnet
  useCustomEntrypoint: false
  customEntrypoint: ""
  seedPeers:
    - /ip4/35.185.66.37/tcp/10105/p2p/12D3KooWQ7Pz3SPizarzx9ZhCJ6jNmQ2iDPgHQxVzRzqYU2SgRSd
    - /ip4/35.237.214.144/tcp/10120/p2p/12D3KooWGtjWnCcvkaSEbKuNbPivEogxqtLWcsJiQtURydptvrsA
  ports:
    client: "8301"
    graphql: "3085"
    metrics: "10001"
    p2p: "10909"
  exposeGraphql: false
  cpuRequest: 6
  memRequest: "12.0Gi"

name: "plain-node-x"

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 5
  initialDelaySeconds: 30

nodeSelector:
  preemptible: false
