apiVersion: v2
name: seed-node
description: A Helm chart for Mina Protocol's seed nodes
type: application
version: 0.4.5
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - enable Artifacthub repository hosting *changes* annotations
    - add CHANGELOG.md for chart version => changelog tracking
dependencies:
  - name: common-utilities
    version: 0.0.7
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- seed
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina
