language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.02 OCAML_RELEASE=3 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.03 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.04 OCAML_RELEASE=2 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.05 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.06 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.07 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.06 OCAML_RELEASE=0 WITH_OPAM=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
  - os: osx
    env: OCAML_VERSION=4.02 OCAML_RELEASE=3 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.03 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.04 OCAML_RELEASE=2 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.05 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.06 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.07 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
