{{ if .Values.mina.runtimeConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.seed.fullname . }}-daemon-config
  labels:
    app: {{ tpl .Values.seed.fullname . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  daemon.json: {{ .Values.mina.runtimeConfig | quote }}
{{- end }}
