apiVersion: v2
name: daemon
description: A Helm chart for Mina Protocol's daemons
type: application
version: 1.0.1
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - Address review feedback
dependencies:
  - name: common-utilities
    version: "*"
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- seed
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/helm/daemon
