deployment:
  testnet: "mainnet"
  name: "helm-example"
  image: gcr.io/o1labs-192920/mina-daemon:1.3.1.2-25388a0-bullseye-mainnet
  runtimeConfig:
  customEntrypoint:
    enabled: false
    entrypoint: ""
  peerListURL: "https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt"
  seedPeers:
    - /dns4/seed-1.mainnet.o1test.net/tcp/10000/p2p/12D3KooWCa1d7G3SkRxy846qTvdAFX69NnoYZ32orWVLqJcDVGHW
    - /dns4/seed-2.mainnet.o1test.net/tcp/10001/p2p/12D3KooWK4NfthViCTyLgVQa1WvqDC1NccVxGruCXCZUt3GqvFvn
    - /dns4/seed-3.mainnet.o1test.net/tcp/10002/p2p/12D3KooWNofeYVAJXA3WGg2qCDhs3GEe71kTmKpFQXRbZmCz1Vr7
    - /dns4/seed-4.mainnet.o1test.net/tcp/10003/p2p/12D3KooWEdBiTUQqxp3jeuWaZkwiSNcFxC6d6Tdq7u2Lf2ZD2Q6X
    - /dns4/seed-5.mainnet.o1test.net/tcp/10004/p2p/12D3KooWL1DJTigSwuKQRfQE3p7puFUqfbHjXbZJ9YBWtMNpr3GU
    - /dns4/seed-6.mainnet.o1test.net/tcp/10005/p2p/12D3KooWHGx4u32n42ub7dJNxAcAhwiA1WDq1Zsjn3k7RsS11pE8

nodes:
  - name: "seed-1"
    class: "seed"
    role: "helm-example"
    replicas: 1
    fullname: "seed-1"
    exposeGraphql: false
    seedFlags: true
    logLevel: Info
    fileLogLevel: Error
    maxConnections: 200
    ports:
      client: "8301"
      graphql: "3085"
      metrics: "10001"
      p2p: "10801"
    archive:
      enabled: false
      address: production-mainnet-archive:3086
    libp2pKeys:
      enabled: true
    minaKeys:
      enabled: false
      produceBlocks: true

requests:
  memory: "80.0Gi"
  cpu: "24"

healthcheck:
  enabled: true
  failureThreshold: 60
  periodSeconds: 5
  initialDelaySeconds: 30
