testnetName: testnet
mina:
  image: openmina/mina:custom-tooling-snark-http-coordinator-mainnet-1.4.0.1-latest
  snarkCoordinatorImage: binier/mina-snark-worker-rs:latest
  privkeyPass:
  exposeGraphql: true
  usePodIp: true
  seedPeersURL: https://storage.googleapis.com/seed-lists/mainnet_seeds.txt
  memRequest: "20.0Gi"
  seedPeers: []
  # seedPeers:
  #   # see resources/seed1.peerid
  #   - /dns4/seed1/tcp/10001/p2p/12D3KooWBT8pyJAfWJhdeGYAtKvcaUmm78ExyZ6uo6BEimYNVat1
  #   # see resources/seed2.peerid
  #   - /dns4/seed2/tcp/10001/p2p/12D3KooWQ2gQb1uoDGymuxtoA8jPdb6SykyP94tEP6FVyXHcM9Ye
  # memRequest: 4Gi
  # cpuRequest: 4
  # optimized: false
  useCustomEntrypoint: true
  customEntrypoint: /scripts/unset-k8s-env.sh

healthcheck:
  enabled: false
  failureThreshold: 60
  periodSeconds: 10
  initialDelaySeconds: 60

plainNodesConfig:
  # the number of plain nodes
  count: 0
  namePrefix: node

seedConfigs:
  - name: seed1
    # see resources/seed1
    libp2pSecret: seed1-libp2p-secret
  - name: seed2
    # see resources/seed2
    libp2pSecret: seed2-libp2p-secret

blockProducerConfigs:
  - name: prod1
    # see resources/key-01
    keypairName: prod1-privkey-secret
    isolated: false
  - name: prod2
    # see resources/key-02
    keypairName: prod2-privkey-secret
    isolated: false
  - name: prod3
    # see resources/key-03
    keypairName: prod3-privkey-secret
    isolated: false
  # - name: prod4
  #   # see resources/key-04
  #   keypairName: prod4-privkey-secret
  #   isolated: false
  # - name: prod5
  #   # see resources/key-05
  #   keypairName: prod5-privkey-secret
  #   isolated: false
  # - name: prod6
  #   # see resources/key-6
  #   keypairName: prod6-privkey-secret
  #   isolated: false
  # - name: prod7
  #   # see resources/key-07
  #   keypairName: prod7-privkey-secret
  #   isolated: false
  # - name: prod8
  #   # see resources/key-08
  #   keypairName: prod8-privkey-secret
  #   isolated: false
  # - name: prod9
  #   # see resources/key-09
  #   keypairName: prod9-privkey-secret
  #   isolated: false
  # - name: prod10
  #   # see resources/key-10
  #   keypairName: prod10-privkey-secret
  #   isolated: false

httpCoordinatedSnarkersConfig:
  # the number of snark workers
  count: 10
  workers: 5
  namePrefix: snarker
  workSelectionAlgorithm: coordinated
  publicKey: B62qosqzHi58Czax2RXfqPhMDzLogBeDVzSpsRDTCN1xeYUfrVy2F8P

# minaSnarkCoordinatorsConfig:
# - name: snarker001
#   publicKey: B62qoGg77bjwPm3kncsjnBChAbeipbotqUCpcGe8FGPbLAJegj6K7od
#   workSelectionAlgorithm: seq
#   workers: 20
# - name: snarker002
#   publicKey: B62qos2NxSras7juEwPVnkoV23YTFvWawyko8pgcf8S5nccTFCzVpdy
#   workSelectionAlgorithm: rand
#   workers: 20
# - name: snarker003
#   publicKey: B62qoGg77bjwPm3kncsjnBChAbeipbotqUCpcGe8FGPbLAJegj6K7od
#   workSelectionAlgorithm: rand
#   workers: 20
# - name: snarker004
#   publicKey: B62qoGg77bjwPm3kncsjnBChAbeipbotqUCpcGe8FGPbLAJegj6K7od
#   workSelectionAlgorithm: rand
#   workers: 10
# - name: snarker005
#   publicKey: B62qoGg77bjwPm3kncsjnBChAbeipbotqUCpcGe8FGPbLAJegj6K7od
#   workSelectionAlgorithm: rand
#   workers: 10
# - name: snarker006
#   publicKey: B62qoGg77bjwPm3kncsjnBChAbeipbotqUCpcGe8FGPbLAJegj6K7od
#   workSelectionAlgorithm: rand
#   workers: 10
# - name: snarker007
#   publicKey: B62qoGg77bjwPm3kncsjnBChAbeipbotqUCpcGe8FGPbLAJegj6K7od
#   workSelectionAlgorithm: rand
#   workers: 10

resources:
  enable: true
  image: adrnagy/mina-node-monitoring:17c9127
  args: ["--executable-name=mina"]
  cpu: "100m"
  memory: "100Mi"

bpfDebugger:
  enable: false
  image: openmina/mina-network-debugger:0aa55313
  cpu: "1500m"
  memory: "4Gi"
  restartMina: false
  runtime: kata-clh

logs:
  enable: true
  image: openmina/mina-logs-service:b5d32468

internalTrace:
  enable: false
  image: openmina/mina-internal-trace-consumer:fec6545

aggregator:
  image: openmina/mina-aggregator:6c99b126
  ciRepo: openmina/mina-daily-testnet

ciFrontend:
  image: directcuteo/ocaml-based-fe:fc0c46f
  nodePort: 31309

nodeSelector:
  preemptible: false
